# Generated by Django 2.2.5 on 2020-02-11 14:09

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    replaces = [('jdma_control', '0001_initial'), ('jdma_control', '0002_auto_20180220_1611'), ('jdma_control', '0003_auto_20180221_0911'), ('jdma_control', '0004_auto_20180221_0947'), ('jdma_control', '0005_auto_20180221_1020'), ('jdma_control', '0006_auto_20180221_1104'), ('jdma_control', '0007_auto_20180221_1155'), ('jdma_control', '0008_auto_20180221_1333'), ('jdma_control', '0009_auto_20180223_0922'), ('jdma_control', '0010_auto_20180223_1145'), ('jdma_control', '0011_auto_20180223_1146'), ('jdma_control', '0012_remove_migration_failure_reason'), ('jdma_control', '0013_auto_20180228_1321'), ('jdma_control', '0014_auto_20180309_1425'), ('jdma_control', '0015_auto_20180312_0940'), ('jdma_control', '0016_auto_20180312_1612'), ('jdma_control', '0017_auto_20180319_1554'), ('jdma_control', '0018_auto_20180320_1036'), ('jdma_control', '0019_auto_20180320_1612'), ('jdma_control', '0020_auto_20180322_1546'), ('jdma_control', '0021_auto_20180329_1326'), ('jdma_control', '0022_auto_20180419_1413'), ('jdma_control', '0023_migrationarchive_packed'), ('jdma_control', '0024_auto_20181005_1001'), ('jdma_control', '0025_auto_20190221_0951'), ('jdma_control', '0026_auto_20190221_1029'), ('jdma_control', '0027_migrationfile_ftype'), ('jdma_control', '0028_migrationfile_link_target'), ('jdma_control', '0029_auto_20191209_1633')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of user - should be same as JASMIN user name', max_length=256, unique=True)),
                ('email', models.EmailField(help_text='Email of user', max_length=256)),
                ('notify', models.BooleanField(default=True, help_text='Switch notifications on / off')),
            ],
        ),
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(choices=[(0, 'elastictape'), (1, 'fakeelastictape'), (2, 'objectstore')], default=0)),
                ('quota_size', sizefield.models.FileSizeField(default=0, help_text='Size of quota allocated to the groupworkspace')),
                ('quota_used', sizefield.models.FileSizeField(default=0, help_text='Size of quota used in the groupworkspace')),
                ('workspace', models.CharField(blank=True, help_text='Name of groupworkspace (GWS)', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupworkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(help_text='Name of groupworkspace (GWS)', max_length=1024)),
                ('path', models.CharField(blank=True, help_text='Path of groupworkspace (optional)', max_length=1024, null=True)),
                ('managers', models.ManyToManyField(help_text='Managers of this groupworkspace', to='jdma_control.User')),
            ],
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUTTING'), (2, 'ON_STORAGE'), (3, 'FAILED'), (4, 'DELETING'), (5, 'DELETED')], default=3)),
                ('external_id', models.CharField(blank=True, help_text='Batch id for external backup system, e.g. elastic tape or object store', max_length=1024, null=True)),
                ('label', models.CharField(blank=True, help_text='Human readable label for request', max_length=1024, null=True)),
                ('registered_date', models.DateTimeField(blank=True, help_text='Date the request was registered with the JDMA', null=True)),
                ('storage', models.ForeignKey(help_text='External storage location of the migration, e.g. elastictape or objectstore', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.StorageQuota')),
                ('user', models.ForeignKey(help_text='User that the migration belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User')),
                ('workspace', models.ForeignKey(help_text='Workspace used for this request', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Groupworkspace')),
                ('common_path', models.CharField(blank=True, help_text='Common path prefix for all files in the filelist', max_length=2048, null=True)),
                ('common_path_group_id', models.IntegerField(blank=True, help_text='gid of original owner of common_path directory', null=True)),
                ('common_path_permission', models.IntegerField(blank=True, help_text='File permissions of original common_path directory', null=True)),
                ('common_path_user_id', models.IntegerField(blank=True, help_text='uid of original owner of common_path directory', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storagequota',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace that this storage quota is for', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Groupworkspace'),
        ),
        migrations.CreateModel(
            name='MigrationArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(help_text='SHA-256 digest of the archive', max_length=64)),
                ('migration', models.ForeignKey(help_text='Migration that this Archive belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration')),
                ('size', sizefield.models.FileSizeField(default=0, help_text='size of file in bytes')),
                ('packed', models.BooleanField(default=False, help_text='Is the archive packed (tarred)?')),
                ('digest_format', models.CharField(default='SHA256', max_length=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storagequota',
            name='storage',
            field=models.IntegerField(choices=[(0, 'elastictape'), (1, 'objectstore')], default=0),
        ),
        migrations.AlterField(
            model_name='storagequota',
            name='storage',
            field=models.IntegerField(choices=[(0, 'elastictape'), (1, 'objectstore'), (2, 'ftp')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='storagequota',
            name='storage',
            field=models.IntegerField(choices=[(0, 'elastictape'), (1, 'objectstore')], db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='MigrationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Relative path to the file (relative to Migration.common_path)', max_length=1024, null=True)),
                ('digest', models.CharField(help_text='Checksum digest of the file', max_length=64, null=True)),
                ('unix_user_id', models.IntegerField(blank=True, help_text='uid of original owner of file', null=True)),
                ('unix_group_id', models.IntegerField(blank=True, help_text='gid of original owner of file', null=True)),
                ('unix_permission', models.IntegerField(blank=True, help_text='File permissions of original file', null=True)),
                ('size', sizefield.models.FileSizeField(default=0, help_text='size of file in bytes')),
                ('archive', models.ForeignKey(help_text='Archive that this File belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.MigrationArchive')),
                ('ftype', models.CharField(default='FILE', help_text='Type of the file', max_length=4)),
                ('link_target', models.CharField(blank=True, help_text='Relative (for LNCM) and absolute (for LNAS) path to the linked file location', max_length=1024, null=True)),
                ('digest_format', models.CharField(default='SHA256', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.IntegerField(choices=[(0, 'PUT'), (1, 'GET'), (2, 'MIGRATE'), (3, 'DELETE')], db_index=True)),
                ('stage', models.IntegerField(choices=[(0, 'PUT_START'), (1, 'PUT_BUILDING'), (2, 'PUT_PENDING'), (3, 'PUT_PACKING'), (4, 'PUTTING'), (5, 'VERIFY_PENDING'), (6, 'VERIFY_GETTING'), (7, 'VERIFYING'), (8, 'PUT_TIDY'), (9, 'PUT_COMPLETED'), (100, 'GET_START'), (101, 'GET_PENDING'), (102, 'GETTING'), (103, 'GET_UNPACKING'), (104, 'GET_RESTORE'), (105, 'GET_TIDY'), (106, 'GET_COMPLETED'), (200, 'DELETE_START'), (201, 'DELETE_PENDING'), (202, 'DELETING'), (203, 'DELETE_TIDY'), (204, 'DELETE_COMPLETED'), (1000, 'FAILED'), (1001, 'FAILED_COMPLETED')], db_index=True, default=1000, help_text='Current upload / download stage')),
                ('date', models.DateTimeField(blank=True, help_text='Date the request was registered with the JDMA', null=True)),
                ('target_path', models.CharField(blank=True, help_text='Target directory path', max_length=1024, null=True)),
                ('credentials', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Credentials required to access the external storage (encrypted)', null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure of request', max_length=1024, null=True)),
                ('migration', models.ForeignKey(help_text='Migration associated with this MigrationRequest', null=True, on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration')),
                ('user', models.ForeignKey(help_text='User that the request belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User')),
                ('last_archive', models.IntegerField(default=0, help_text='Last completed uploaded / downloaded archive')),
                ('locked', models.BooleanField(default=False, help_text='Migration is locked for processing')),
                ('filelist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, unique=True), blank=True, help_text='List of files for uploading or downloading', null=True, size=None)),
                ('transfer_id', models.CharField(blank=True, help_text='Tranfer id for external backup system, e.g. elastic tape', max_length=1024, null=True)),
            ],
        ),
    ]
