# Generated by Django 2.0.2 on 2018-02-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0002_auto_20180220_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupworkspacequota',
            name='storage_quota',
            field=models.ForeignKey(help_text='Quotas for backend storage for this groupworkspace', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.StorageQuota'),
        ),
    ]
