# Generated by Django 2.0.2 on 2018-02-23 09:22

from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0008_auto_20180221_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(help_text='SHA-256 digest of the block', max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupworkspace',
            name='storage_quota',
        ),
        migrations.AddField(
            model_name='migrationfile',
            name='size',
            field=sizefield.models.FileSizeField(default=0, help_text='size of file in bytes'),
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='last_block',
            field=models.IntegerField(default=0, help_text='Last completed uploaded / downloaded block'),
        ),
        migrations.AlterField(
            model_name='groupworkspace',
            name='managers',
            field=models.ManyToManyField(help_text='Managers of this groupworkspace', to='jdma_control.User'),
        ),
        migrations.AlterField(
            model_name='migration',
            name='user',
            field=models.ForeignKey(help_text='User that the migration belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User'),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='digest',
            field=models.CharField(help_text='SHA-256 digest of the file', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='path',
            field=models.CharField(help_text='Absolute path to the file', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_STORAGE'), (5, 'PUTTING'), (1, 'GET_PENDING'), (2, 'GETTING'), (3, 'ON_DISK'), (4, 'FAILED')], default=0, help_text='Current upload / download stage'),
        ),
        migrations.AlterField(
            model_name='storagequota',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace that this storage quota is for', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Groupworkspace'),
        ),
    ]
