# Generated by Django 2.0.2 on 2018-02-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0009_auto_20180223_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(help_text='SHA-256 digest of the block', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='MigrationBlock',
        ),
        migrations.RenameField(
            model_name='migrationrequest',
            old_name='last_block',
            new_name='last_archive',
        ),
        migrations.AlterField(
            model_name='migration',
            name='external_id',
            field=models.CharField(blank=True, help_text='Batch id for external backup system, e.g. elastic tape or object store', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='migrationarchive',
            name='migration',
            field=models.ForeignKey(help_text='Migration that this Archive belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration'),
        ),
        migrations.AddField(
            model_name='migrationfile',
            name='archive',
            field=models.ForeignKey(help_text='Archive that this File belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='jdma_control.MigrationArchive'),
        ),
    ]
