# Generated by Django 2.0.2 on 2018-02-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0012_remove_migration_failure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationarchive',
            name='digest',
            field=models.CharField(help_text='SHA-256 digest of the archive', max_length=64),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='last_archive',
            field=models.IntegerField(default=0, help_text='Last completed uploaded / downloaded archive'),
        ),
    ]
