# Generated by Django 2.0.2 on 2018-03-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0014_auto_20180309_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUTTING'), (2, 'ON_STORAGE'), (3, 'FAILED')], default=3),
        ),
    ]
