# Generated by Django 2.0.2 on 2018-03-12 16:12

from django.db import migrations, models
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0015_auto_20180312_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationarchive',
            name='size',
            field=sizefield.models.FileSizeField(default=0, help_text='size of file in bytes'),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'PUT_START'), (1, 'PUT_PENDING'), (2, 'PUT_PACKING'), (3, 'PUTTING'), (4, 'VERIFY_PENDING'), (5, 'VERIFY_GETTING'), (6, 'VERIFYING'), (7, 'PUT_TIDY'), (8, 'PUT_COMPLETED'), (100, 'GET_START'), (101, 'GET_PENDING'), (102, 'GETTING'), (103, 'GET_UNPACKING'), (104, 'GET_RESTORE'), (105, 'GET_TIDY'), (106, 'GET_COMPLETED'), (200, 'FAILED')], default=200, help_text='Current upload / download stage'),
        ),
    ]
