# Generated by Django 2.0.2 on 2018-03-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0016_auto_20180312_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='common_path',
            field=models.CharField(blank=True, help_text='Common path prefix for all files in the filelist', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='migration',
            name='locked',
            field=models.BooleanField(default=False, help_text='Migration is locked for processing'),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'PUT_START'), (1, 'PUT_PENDING'), (2, 'PUT_PACKING'), (3, 'PUTTING'), (4, 'VERIFY_PENDING'), (5, 'VERIFY_GETTING'), (6, 'VERIFYING'), (7, 'PUT_TIDY'), (8, 'PUT_COMPLETED'), (100, 'GET_START'), (101, 'GET_PENDING'), (102, 'GETTING'), (103, 'GET_UNPACKING'), (104, 'GET_RESTORE'), (105, 'GET_TIDY'), (106, 'GET_COMPLETED'), (1000, 'FAILED')], default=1000, help_text='Current upload / download stage'),
        ),
    ]
