# Generated by Django 2.0.2 on 2018-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0017_auto_20180319_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migration',
            name='locked',
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='locked',
            field=models.BooleanField(default=False, help_text='Migration is locked for processing'),
        ),
    ]
