# Generated by Django 2.1.7 on 2019-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0027_migrationfile_ftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationfile',
            name='link_target',
            field=models.CharField(help_text='Absolute path to the linked file location', max_length=1024, null=True),
        ),
    ]
