# Generated by Django 2.2.6 on 2019-12-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0028_migrationfile_link_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationarchive',
            name='digest_format',
            field=models.CharField(default='SHA256', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='migrationfile',
            name='digest_format',
            field=models.CharField(default='SHA256', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='digest',
            field=models.CharField(help_text='Checksum digest of the file', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='link_target',
            field=models.CharField(blank=True, help_text='Relative (for LNCM) and absolute (for LNAS) path to the linked file location', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'PUT_START'), (1, 'PUT_BUILDING'), (2, 'PUT_PENDING'), (3, 'PUT_PACKING'), (4, 'PUTTING'), (5, 'VERIFY_PENDING'), (6, 'VERIFY_GETTING'), (7, 'VERIFYING'), (8, 'PUT_TIDY'), (9, 'PUT_COMPLETED'), (100, 'GET_START'), (101, 'GET_PENDING'), (102, 'GETTING'), (103, 'GET_UNPACKING'), (104, 'GET_RESTORE'), (105, 'GET_TIDY'), (106, 'GET_COMPLETED'), (200, 'DELETE_START'), (201, 'DELETE_PENDING'), (202, 'DELETING'), (203, 'DELETE_TIDY'), (204, 'DELETE_COMPLETED'), (1000, 'FAILED'), (1001, 'FAILED_COMPLETED')], db_index=True, default=1000, help_text='Current upload / download stage'),
        ),
    ]
