# Generated by Django 2.0 on 2017-12-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(help_text='Workspace used for this request', max_length=2024)),
                ('stage', models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUT_PENDING'), (2, 'PUTTING'), (3, 'VERIFY_PENDING'), (4, 'VERIFY_GETTING'), (5, 'VERIFYING'), (6, 'ON_TAPE'), (7, 'FAILED')], default=7)),
                ('permission', models.IntegerField(choices=[(0, 'PRIVATE'), (1, 'GROUP'), (2, 'ALL')], default=0)),
                ('external_id', models.IntegerField(blank=True, help_text='Batch id for external backup system, e.g. elastic tape or object store', null=True)),
                ('label', models.CharField(blank=True, help_text='Human readable label for request', max_length=2024, null=True)),
                ('registered_date', models.DateTimeField(blank=True, help_text='Date the request was registered with the JDMA', null=True)),
                ('original_path', models.CharField(help_text='Original directory path', max_length=2024, unique=True)),
                ('unix_user_id', models.CharField(blank=True, help_text='uid of original owner of directory', max_length=256, null=True)),
                ('unix_group_id', models.CharField(blank=True, help_text='gid of original owner of directory', max_length=256, null=True)),
                ('unix_permission', models.IntegerField(blank=True, help_text='File permissions of original directory', null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure of request', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Absolute path to the file', max_length=2024)),
                ('digest', models.CharField(help_text='SHA-256 digest of the file', max_length=64)),
                ('migration', models.ForeignKey(help_text='Migration associated with this MigrationFile', null=True, on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.IntegerField(choices=[(0, 'PUT'), (1, 'GET')])),
                ('stage', models.IntegerField(choices=[(0, 'ON_TAPE'), (1, 'GET_PENDING'), (2, 'GETTING'), (3, 'ON_DISK'), (4, 'FAILED')], default=0)),
                ('date', models.DateTimeField(blank=True, help_text='Date the request was registered with the JDMA', null=True)),
                ('target_path', models.CharField(blank=True, help_text='Target directory path', max_length=2024, null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure of request', max_length=1024, null=True)),
                ('migration', models.ForeignKey(help_text='Migration associated with this MigrationRequest', null=True, on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of user - should be same as JASMIN user name', max_length=254)),
                ('email', models.EmailField(help_text='Email of user', max_length=254)),
                ('notify', models.BooleanField(default=True, help_text='Switch notifications on / off')),
            ],
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='user',
            field=models.ForeignKey(help_text='User that the request belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User'),
        ),
        migrations.AddField(
            model_name='migration',
            name='user',
            field=models.ForeignKey(help_text='User that the directory belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User'),
        ),
    ]
