# Generated by Django 2.2.5 on 2020-02-11 15:31

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupworkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(help_text='Name of groupworkspace (GWS)', max_length=1024)),
                ('path', models.CharField(blank=True, help_text='Path of groupworkspace (optional)', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUTTING'), (2, 'ON_STORAGE'), (3, 'FAILED'), (4, 'DELETING'), (5, 'DELETED')], default=3)),
                ('external_id', models.CharField(blank=True, help_text='Batch id for external backup system, e.g. elastic tape or object store', max_length=1024, null=True)),
                ('label', models.CharField(blank=True, help_text='Human readable label for request', max_length=1024, null=True)),
                ('registered_date', models.DateTimeField(blank=True, help_text='Date the request was registered with the JDMA', null=True)),
                ('common_path', models.CharField(blank=True, help_text='Common path prefix for all files in the filelist', max_length=2048, null=True)),
                ('common_path_user_id', models.IntegerField(blank=True, help_text='uid of original owner of common_path directory', null=True)),
                ('common_path_group_id', models.IntegerField(blank=True, help_text='gid of original owner of common_path directory', null=True)),
                ('common_path_permission', models.IntegerField(blank=True, help_text='File permissions of original common_path directory', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(help_text='Digest of the archive', max_length=64)),
                ('digest_format', models.CharField(default='SHA256', max_length=32, null=True)),
                ('size', sizefield.models.FileSizeField(default=0, help_text='size of file in bytes')),
                ('packed', models.BooleanField(default=False, help_text='Is the archive packed (tarred)?')),
                ('migration', models.ForeignKey(help_text='Migration that this Archive belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of user - should be same as JASMIN user name', max_length=256, unique=True)),
                ('email', models.EmailField(help_text='Email of user', max_length=256)),
                ('notify', models.BooleanField(default=True, help_text='Switch notifications on / off')),
            ],
        ),
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(choices=[(0, 'elastictape'), (1, 'objectstore')], db_index=True, default=0)),
                ('quota_size', sizefield.models.FileSizeField(default=0, help_text='Size of quota allocated to the groupworkspace')),
                ('quota_used', sizefield.models.FileSizeField(default=0, help_text='Size of quota used in the groupworkspace')),
                ('workspace', models.ForeignKey(help_text='Workspace that this storage quota is for', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Groupworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.IntegerField(choices=[(0, 'PUT'), (1, 'GET'), (2, 'MIGRATE'), (3, 'DELETE')], db_index=True)),
                ('stage', models.IntegerField(choices=[(0, 'PUT_START'), (1, 'PUT_BUILDING'), (2, 'PUT_PENDING'), (3, 'PUT_PACKING'), (4, 'PUTTING'), (5, 'VERIFY_PENDING'), (6, 'VERIFY_GETTING'), (7, 'VERIFYING'), (8, 'PUT_TIDY'), (9, 'PUT_COMPLETED'), (100, 'GET_START'), (101, 'GET_PENDING'), (102, 'GETTING'), (103, 'GET_UNPACKING'), (104, 'GET_RESTORE'), (105, 'GET_TIDY'), (106, 'GET_COMPLETED'), (200, 'DELETE_START'), (201, 'DELETE_PENDING'), (202, 'DELETING'), (203, 'DELETE_TIDY'), (204, 'DELETE_COMPLETED'), (1000, 'FAILED'), (1001, 'FAILED_COMPLETED')], db_index=True, default=1000, help_text='Current upload / download stage')),
                ('date', models.DateTimeField(blank=True, help_text='Date the request was registered with the JDMA', null=True)),
                ('target_path', models.CharField(blank=True, help_text='Target directory path', max_length=1024, null=True)),
                ('credentials', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Credentials required to access the external storage (encrypted)', null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure of request', max_length=1024, null=True)),
                ('filelist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, unique=True), blank=True, help_text='List of files for uploading or downloading', null=True, size=None)),
                ('last_archive', models.IntegerField(default=0, help_text='Last completed uploaded / downloaded archive')),
                ('transfer_id', models.CharField(blank=True, help_text='Tranfer id for external backup system, e.g. elastic tape', max_length=1024, null=True)),
                ('locked', models.BooleanField(default=False, help_text='Migration is locked for processing')),
                ('migration', models.ForeignKey(help_text='Migration associated with this MigrationRequest', null=True, on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration')),
                ('user', models.ForeignKey(help_text='User that the request belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Relative path to the file (relative to Migration.common_path)', max_length=1024, null=True)),
                ('digest', models.CharField(help_text='Checksum digest of the file', max_length=64, null=True)),
                ('digest_format', models.CharField(default='SHA256', max_length=32, null=True)),
                ('size', sizefield.models.FileSizeField(default=0, help_text='size of file in bytes')),
                ('ftype', models.CharField(default='FILE', help_text='Type of the file', max_length=4)),
                ('link_target', models.CharField(blank=True, help_text='Relative (for LNCM) and absolute (for LNAS) path to the linked file location', max_length=1024, null=True)),
                ('unix_user_id', models.IntegerField(blank=True, help_text='uid of original owner of file', null=True)),
                ('unix_group_id', models.IntegerField(blank=True, help_text='gid of original owner of file', null=True)),
                ('unix_permission', models.IntegerField(blank=True, help_text='File permissions of original file', null=True)),
                ('archive', models.ForeignKey(help_text='Archive that this File belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.MigrationArchive')),
            ],
        ),
        migrations.AddField(
            model_name='migration',
            name='storage',
            field=models.ForeignKey(help_text='External storage location of the migration, e.g. elastictape or objectstore', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.StorageQuota'),
        ),
        migrations.AddField(
            model_name='migration',
            name='user',
            field=models.ForeignKey(help_text='User that the migration belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User'),
        ),
        migrations.AddField(
            model_name='migration',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace used for this request', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Groupworkspace'),
        ),
        migrations.AddField(
            model_name='groupworkspace',
            name='managers',
            field=models.ManyToManyField(help_text='Managers of this groupworkspace', to='jdma_control.User'),
        ),
    ]
