# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(help_text='Workspace used for this request', max_length=2024)),
                ('stage', models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUT_PENDING'), (2, 'PUTTING'), (3, 'ON_TAPE'), (4, 'GET_PENDING'), (5, 'GETTING'), (6, 'FAILED')])),
                ('et_id', models.IntegerField(blank=True, help_text='Elastic tape batch id', null=True)),
                ('label', models.CharField(blank=True, help_text='Human readable label for request', max_length=2024, null=True)),
                ('registered_date', models.DateTimeField(blank=True, help_text='Date the request was registered with the JDMA', null=True)),
                ('original_path', models.CharField(help_text='Original directory path', max_length=2024, unique=True)),
                ('unix_user_id', models.CharField(blank=True, help_text='uid of original owner of directory', max_length=256, null=True)),
                ('unix_group_id', models.CharField(blank=True, help_text='gid of original owner of directory', max_length=256, null=True)),
                ('unix_permission', models.IntegerField(blank=True, help_text='File permissions of original directory', null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.IntegerField(choices=[(0, 'PUT'), (1, 'GET'), (2, 'VERIFY')])),
                ('date', models.DateTimeField(blank=True, help_text='Date the request was registered with the JDMA', null=True)),
                ('target_path', models.CharField(blank=True, help_text='Target directory path', max_length=2024, null=True)),
                ('migration', models.ForeignKey(help_text='Migration associated with this MigrationRequest', null=True, on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of user - should be same as JASMIN user name', max_length=254)),
                ('email', models.EmailField(help_text='Email of user', max_length=254)),
                ('notify', models.BooleanField(default=True, help_text='Switch notifications on / off')),
            ],
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='user',
            field=models.ForeignKey(help_text='User that the request belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User'),
        ),
        migrations.AddField(
            model_name='migration',
            name='user',
            field=models.ForeignKey(help_text='User that the directory belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.User'),
        ),
    ]
