# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0001_squashed_0008_auto_20171012_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='permission',
            field=models.IntegerField(choices=[(0, 'PRIVATE'), (1, 'GROUP'), (2, 'ALL')], default=0),
        ),
    ]
