# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUT_PENDING'), (2, 'PUTTING'), (3, 'VERIFY_PENDING'), (4, 'VERIFY_GETTING'), (5, 'VERIFYING'), (6, 'ON_STORAGE'), (7, 'FAILED')], default=7),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_STORAGE'), (1, 'GET_PENDING'), (2, 'GETTING'), (3, 'ON_DISK'), (4, 'FAILED')], default=0),
        ),
    ]
