# Generated by Django 2.0.2 on 2018-02-20 16:11

from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(choices=[(0, 'elastictape'), (1, 'fakeelastictape'), (2, 'objectstore')], default=0)),
                ('quota_size', sizefield.models.FileSizeField(default=0, help_text='Size of quota allocated to the groupworkspace')),
                ('quota_used', sizefield.models.FileSizeField(default=0, help_text='Size of quota allocated to user, in (bytes day)')),
            ],
        ),
        migrations.AddField(
            model_name='groupworkspacequota',
            name='path',
            field=models.CharField(blank=True, help_text='Path of groupworkspace (optional)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='groupworkspacequota',
            name='workspace',
            field=models.CharField(help_text='Name of groupworkspace (GWS)', max_length=1024),
        ),
        migrations.AddField(
            model_name='groupworkspacequota',
            name='storage_quota',
            field=models.ForeignKey(default=None, help_text='Quotas for backend storage for this groupworkspace', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.StorageQuota'),
        ),
    ]
