# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Reason for failure of request', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='migration',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUT_PENDING'), (2, 'PUTTING'), (3, 'VERIFY_PENDING'), (4, 'VERIFYING'), (5, 'ON_TAPE'), (6, 'GET_PENDING'), (7, 'GETTING'), (8, 'FAILED')]),
        ),
    ]
