# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0002_auto_20171208_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migration',
            name='permission',
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'PUT'), (1, 'GET'), (2, 'MIGRATE')]),
        ),
    ]
