# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0002_auto_20171006_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUT_PENDING'), (2, 'PUTTING'), (3, 'VERIFY_PENDING'), (4, 'VERIFY_GET'), (5, 'VERIFYING'), (6, 'ON_TAPE'), (7, 'GET_PENDING'), (8, 'GETTING'), (9, 'FAILED')]),
        ),
    ]
