# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0003_auto_20171221_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='storage',
            field=models.CharField(default='Elastic Tape', help_text='External storage location of the migration, e.g. elastictape or objectstore', max_length=256),
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='access_key',
            field=models.CharField(blank=True, default='', help_text='Access key or username for the external storage', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='extra_key',
            field=models.CharField(blank=True, default='', help_text='An extra info for the external storage', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='secret_key',
            field=models.CharField(blank=True, default='', help_text='Secret key or password for the external storage', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='storage',
            field=models.CharField(default='Elastic Tape', help_text='External storage location of the migration, e.g. elastictape or objectstore', max_length=256),
        ),
    ]
