# Generated by Django 2.0.2 on 2018-02-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0003_auto_20180221_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupworkspacequota',
            name='storage_quota',
        ),
        migrations.AddField(
            model_name='storagequota',
            name='workspace',
            field=models.ForeignKey(default=None, help_text='Groupworkspace of the quota', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.GroupworkspaceQuota', unique=True),
        ),
    ]
