# Generated by Django 2.0.2 on 2018-02-21 10:20

from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0004_auto_20180221_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupworkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(help_text='Name of groupworkspace (GWS)', max_length=1024)),
                ('path', models.CharField(blank=True, help_text='Path of groupworkspace (optional)', max_length=1024, null=True)),
                ('manager_email', models.EmailField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='storagequota',
            name='workspace',
        ),
        migrations.AlterField(
            model_name='migration',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace used for this request', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Groupworkspace'),
        ),
        migrations.AlterField(
            model_name='storagequota',
            name='quota_used',
            field=sizefield.models.FileSizeField(default=0, help_text='Size of quota used in the groupworkspace'),
        ),
        migrations.DeleteModel(
            name='GroupworkspaceQuota',
        ),
        migrations.AddField(
            model_name='groupworkspace',
            name='storage_quota',
            field=models.ManyToManyField(help_text='Quotas for backend storage for this groupworkspace', to='jdma_control.StorageQuota'),
        ),
    ]
