# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0004_auto_20180205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='storage',
            field=models.CharField(default='elastictape', help_text='External storage location of the migration, e.g. elastictape or objectstore', max_length=256),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='storage',
            field=models.CharField(default='elastictape', help_text='External storage location of the migration, e.g. elastictape or objectstore', max_length=256),
        ),
    ]
