# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0004_auto_20171010_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationrequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'PUT'), (1, 'GET')]),
        ),
    ]
