# Generated by Django 2.0.2 on 2018-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0005_auto_20180221_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupworkspace',
            name='manager_email',
        ),
        migrations.AddField(
            model_name='groupworkspace',
            name='managers',
            field=models.ManyToManyField(help_text='Manages of this groupworkspace', to='jdma_control.User'),
        ),
    ]
