# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0005_auto_20171011_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrequest',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Reason for failure of request', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'GET_PENDING'), (1, 'GETTING'), (2, 'ON_DISK'), (3, 'FAILED')], default=3),
        ),
        migrations.AlterField(
            model_name='migration',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUT_PENDING'), (2, 'PUTTING'), (3, 'VERIFY_PENDING'), (4, 'VERIFY_GETTING'), (5, 'VERIFYING'), (6, 'ON_TAPE'), (7, 'FAILED')], default=7),
        ),
    ]
