# Generated by Django 2.0.2 on 2018-02-13 11:57

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0005_auto_20180205_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationrequest',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='migrationrequest',
            name='extra_key',
        ),
        migrations.RemoveField(
            model_name='migrationrequest',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='migrationrequest',
            name='credentials',
            field=django.contrib.postgres.fields.hstore.HStoreField(help_text='Credentials required to access the external storage (encrypted)', null=True),
        ),
    ]
