# Generated by Django 2.0.2 on 2018-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0007_auto_20180221_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationrequest',
            name='storage',
        ),
        migrations.AddField(
            model_name='storagequota',
            name='workspace',
            field=models.CharField(blank=True, help_text='Name of groupworkspace (GWS)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Name of user - should be same as JASMIN user name', max_length=256, unique=True),
        ),
    ]
