# Generated by Django 2.0.2 on 2018-02-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0010_auto_20180223_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationarchive',
            name='migration',
            field=models.ForeignKey(help_text='Migration that this Archive belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.Migration'),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='archive',
            field=models.ForeignKey(help_text='Archive that this File belongs to', on_delete=django.db.models.deletion.CASCADE, to='jdma_control.MigrationArchive'),
        ),
    ]
