# Generated by Django 2.0.2 on 2018-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0013_auto_20180228_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'ON_STORAGE'), (2, 'FAILED')], default=2),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'PUT_START'), (1, 'PUT_PENDING'), (2, 'PUT_PACK'), (3, 'PUTTING'), (4, 'VERIFY_PENDING'), (5, 'VERIFY_GETTING'), (6, 'VERIFYING'), (7, 'PUT_TIDY'), (8, 'PUT_COMPLETED'), (100, 'GET_START'), (101, 'GET_PENDING'), (102, 'GETTING'), (103, 'GET_UNPACK'), (104, 'GET_RESTORE'), (105, 'GET_TIDY'), (106, 'GET_COMPLETED'), (200, 'FAILED')], default=200, help_text='Current upload / download stage'),
        ),
    ]
