# Generated by Django 2.0.2 on 2018-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0018_auto_20180320_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='common_path_group_id',
            field=models.CharField(blank=True, help_text='gid of original owner of common_path directory', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='migration',
            name='common_path_permission',
            field=models.IntegerField(blank=True, help_text='File permissions of original common_path directory', null=True),
        ),
        migrations.AddField(
            model_name='migration',
            name='common_path_user_id',
            field=models.CharField(blank=True, help_text='uid of original owner of common_path directory', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='path',
            field=models.CharField(help_text='Relative path to the file (relative to Migration.common_path)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='unix_group_id',
            field=models.CharField(blank=True, help_text='gid of original owner of file', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='unix_permission',
            field=models.IntegerField(blank=True, help_text='File permissions of original file', null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='unix_user_id',
            field=models.CharField(blank=True, help_text='uid of original owner of file', max_length=256, null=True),
        ),
    ]
