# Generated by Django 2.0.2 on 2018-03-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0019_auto_20180320_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='stage',
            field=models.IntegerField(choices=[(0, 'ON_DISK'), (1, 'PUTTING'), (2, 'ON_STORAGE'), (3, 'FAILED'), (4, 'DELETING')], default=3),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'PUT'), (1, 'GET'), (2, 'MIGRATE'), (3, 'DELETE')]),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'PUT_START'), (1, 'PUT_PENDING'), (2, 'PUT_PACKING'), (3, 'PUTTING'), (4, 'VERIFY_PENDING'), (5, 'VERIFY_GETTING'), (6, 'VERIFYING'), (7, 'PUT_TIDY'), (8, 'PUT_COMPLETED'), (100, 'GET_START'), (101, 'GET_PENDING'), (102, 'GETTING'), (103, 'GET_UNPACKING'), (104, 'GET_RESTORE'), (105, 'GET_TIDY'), (106, 'GET_COMPLETED'), (200, 'DELETE_START'), (201, 'DELETE_PENDING'), (202, 'DELETING'), (203, 'DELETE_TIDY'), (204, 'DELETE_COMPLETED'), (1000, 'FAILED')], default=1000, help_text='Current upload / download stage'),
        ),
    ]
