# Generated by Django 2.0.4 on 2018-04-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0021_auto_20180329_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrequest',
            name='transfer_id',
            field=models.CharField(blank=True, help_text='Tranfer id for external backup system, e.g. elastic tape', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='storagequota',
            name='storage',
            field=models.IntegerField(choices=[(0, 'elastictape'), (1, 'objectstore')], default=0),
        ),
    ]
