# Generated by Django 2.1.2 on 2018-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdma_control', '0023_migrationarchive_packed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='common_path_group_id',
            field=models.IntegerField(blank=True, help_text='gid of original owner of common_path directory', null=True),
        ),
        migrations.AlterField(
            model_name='migration',
            name='common_path_user_id',
            field=models.IntegerField(blank=True, help_text='uid of original owner of common_path directory', null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='unix_group_id',
            field=models.IntegerField(blank=True, help_text='gid of original owner of file', null=True),
        ),
        migrations.AlterField(
            model_name='migrationfile',
            name='unix_user_id',
            field=models.IntegerField(blank=True, help_text='uid of original owner of file', null=True),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'PUT'), (1, 'GET'), (2, 'MIGRATE'), (3, 'DELETE')], db_index=True),
        ),
        migrations.AlterField(
            model_name='migrationrequest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'PUT_START'), (1, 'PUT_PENDING'), (2, 'PUT_PACKING'), (3, 'PUTTING'), (4, 'VERIFY_PENDING'), (5, 'VERIFY_GETTING'), (6, 'VERIFYING'), (7, 'PUT_TIDY'), (8, 'PUT_COMPLETED'), (100, 'GET_START'), (101, 'GET_PENDING'), (102, 'GETTING'), (103, 'GET_UNPACKING'), (104, 'GET_RESTORE'), (105, 'GET_TIDY'), (106, 'GET_COMPLETED'), (200, 'DELETE_START'), (201, 'DELETE_PENDING'), (202, 'DELETING'), (203, 'DELETE_TIDY'), (204, 'DELETE_COMPLETED'), (1000, 'FAILED')], db_index=True, default=1000, help_text='Current upload / download stage'),
        ),
        migrations.AlterField(
            model_name='storagequota',
            name='storage',
            field=models.IntegerField(choices=[(0, 'elastictape'), (1, 'objectstore'), (2, 'ftp')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of user - should be same as JASMIN user name', max_length=256, unique=True),
        ),
    ]
