#!/usr/bin/env bash
# Run the scripts in the order required to test the upload to the external storage

# location of the python executable in the venv
PYTHON=/home/vagrant/JDMA/venv/bin/python3.6
MANAGE="$PYTHON $PWD/../manage.py"

echo "1. jdma_lock PUT_START->PUT_PENDING"
$MANAGE runscript jdma_lock

echo "2. jdma_transfer PUT_PENDING->PUT_PACKING"
$MANAGE runscript jdma_transfer

echo "3. jdma_pack PUT_PACKING->PUTTING"
$MANAGE runscript jdma_pack

echo "4. jdma_transfer PUTTING->PUTTING"
$MANAGE runscript jdma_transfer

echo "4.5 jdma_monitor PUTTING->VERIFY_PENDING"
$MANAGE runscript jdma_monitor

echo "5. jdma_transfer VERIFY_PENDING->VERIFY_GETTING"
$MANAGE runscript jdma_transfer

echo "6. jdma_transfer VERIFY_GETTING->VERIFY_GETTING"
$MANAGE runscript jdma_transfer

echo "6a. jdma_monitor VERIFY_GETTING->VERIFYING"
$MANAGE runscript jdma_monitor

echo "7. jdma_verify VERIFYING->PUT_TIDY"
$MANAGE runscript jdma_verify

echo "8. jdma_tidy PUT_TIDY->PUT_COMPLETED"
$MANAGE runscript jdma_tidy

echo "9. jdma_tidy PUT_COMPLETED->deleted"
$MANAGE runscript jdma_tidy
