#!/usr/bin/env bash
# location of the python executable in the venv
PYTHON=/home/vagrant/JDMA/venv/bin/python3.6
MANAGE="$PYTHON $PWD/../manage.py"

# Run the scripts in the order required to test the download from the external storage
echo "10. jdma_lock GET_START->GET_PENDING"
$MANAGE runscript jdma_lock

echo "11. jdma_transfer GET_PENDING->GETTING"
$MANAGE runscript jdma_transfer

echo "12. jdma_transfer GETTING->GETTING"
$MANAGE runscript jdma_transfer

echo "12a.jdma_monitor GETTING->GET_UNPACK"
$MANAGE runscript jdma_monitor

echo "13. jdma_packing GET_UNPACK->GET_RESTORE"
$MANAGE runscript jdma_pack

echo "14. jdma_transfer GET_RESTORE->GET_TIDY"
$MANAGE runscript jdma_transfer

echo "15. jdma_tidy GET_TIDY->GET_COMPLETED"
$MANAGE runscript jdma_tidy

echo "16. jdma_tidy GET_COMPLETED->deleted"
$MANAGE runscript jdma_tidy
